apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: ptpconfigs.ptp.openshift.io
spec:
  group: ptp.openshift.io
  names:
    kind: PtpConfig
    listKind: PtpConfigList
    plural: ptpconfigs
    singular: ptpconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: PtpConfig is the Schema for the ptpconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PtpConfigSpec defines the desired state of PtpConfig
            properties:
              profile:
                items:
                  properties:
                    interface:
                      type: string
                    name:
                      type: string
                    phc2sysOpts:
                      type: string
                    ptp4lConf:
                      type: string
                    ptp4lOpts:
                      type: string
                    ptpClockThreshold:
                      properties:
                        holdOverTimeout:
                          default: 5
                          description: clock state to stay in holdover state in secs
                          format: int64
                          type: integer
                        maxOffsetThreshold:
                          default: 100
                          description: max offset in nano secs
                          format: int64
                          type: integer
                        minOffsetThreshold:
                          default: -100
                          description: min offset in nano secs
                          format: int64
                          type: integer
                      type: object
                    ptpSchedulingPolicy:
                      enum:
                      - SCHED_OTHER
                      - SCHED_FIFO
                      type: string
                    ptpSchedulingPriority:
                      format: int64
                      maximum: 65
                      minimum: 1
                      type: integer
                    ts2PhcConf:
                      type: string
                    ts2PhcOpts:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              recommend:
                items:
                  properties:
                    match:
                      items:
                        properties:
                          nodeLabel:
                            type: string
                          nodeName:
                            type: string
                        type: object
                      type: array
                    priority:
                      format: int64
                      type: integer
                    profile:
                      type: string
                  required:
                  - priority
                  - profile
                  type: object
                type: array
            required:
            - profile
            - recommend
            type: object
          status:
            description: PtpConfigStatus defines the observed state of PtpConfig
            properties:
              matchList:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                items:
                  properties:
                    nodeName:
                      type: string
                    profile:
                      type: string
                  required:
                  - nodeName
                  - profile
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
