apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-manager-rolebinding
  namespace: openshift-ptp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-manager-role
subjects:
- kind: ServiceAccount
  name: ptp-operator
  namespace: openshift-ptp
